### ISSUE TITLE
Pull Request 'trigger build' stucks (XSRF Check Failed)

### ISSUE THREAD

**Issue by mr-const** [Nerdwin15/stash-jenkins-postreceive-webhook#155] opened 2015-10-20 14:48 UTC
I've upgraded stash to bitbucket 4.0 and stash webhook plugin to bitbucket webhook. After that PR's 'trigger build' is broken. 
When I create first PR, trigger build works as expected, but when I press that button after PR update (i.e. added new commit) - it stucks. I checked button press with web debugger and got following POST error:
```
Request URL: 	https://bitbucket.installation.url/git/rest/jenkins/latest/projects/AG/repos/proj-android/triggerJenkins?branches=feature/AAA-122-Branch&sha1=aff48cea08ec953c17b1a732aa1509c9c6de9ba5
Request Method: 	POST
Status Code: 	HTTP/1.1 403 Forbidden
Request Headers 17:26:32.000
X-Requested-With:	XMLHttpRequest
User-Agent:	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0
Referer:	https://bitbucket.installation.url/git/projects/AG/repos/proj-android/pull-requests/233/overview
Pragma:	no-cache
Host:	bitbucket.installation.url
Content-Length:	0
Connection:	keep-alive
Cache-Control:	no-cache
Accept-Language:	en-US,en;q=0.5
Accept-Encoding:	gzip, deflate
Accept:	*/*
Sent Cookie
JSESSIONID:	1AD3CB9B6103669EA9F579CC15B78D44
AJS.conglomerate.cookie:	"|LAST_TEMPLATES_KEY={\"1\":\"DEFAULT\"}"
_ga:	GA1.2.721443465.1421842694
_atl_bitbucket_remember_me:	N2U2MWUxOTRmYmYxYzJlMjRlMzFiNjljMjM2NzFiM2VjMWY0YzMxMzoyODgyOGIwMzc5MmJjYTU4ZTJkZTQ0YWQ5ZDk3NmJhZTU2MzY5MjU1
__utmz:	2435749.1423493971.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
__utma:	2435749.721443465.1421842694.1436184975.1438262421.8
Response Headers Δ40ms
x-content-type-options:	nosniff
X-AUSERNAME:	username
X-AUSERID:	1
X-ASESSIONID:	zv02u9
X-ASEN:	SEN-4559999
X-AREQUESTID:	@8ZZTJCx1044x6720x0
Vary:	Accept-Encoding
Transfer-Encoding:	chunked
Server:	nginx/1.4.6 (Ubuntu)
Date:	Tue, 20 Oct 2015 14:24:47 GMT
Content-Type:	text/html
Content-Encoding:	gzip
Connection:	keep-alive
Response Body Δ0ms
XSRF check failed
```

**Comment by frami** [comment] 2015-10-21 04:55
We have the same issue. I opened an issue (https://jira.atlassian.com/browse/BSERV-7914) at atlassian, but they mean that the addon needs to be updated:
>If the add-on is making any requests into Bitbucket Server which are not declared to accept a content-type of application/json, then the X-Atlassian-Token: no-check header will need to be set. See https://confluence.atlassian.com/bitbucketserver/how-to-update-your-add-on-779302412.html#Howtoupdateyouradd-on-XSRFProtectionenabledbydefault for more information.

**Comment by lobermann** [comment] 2015-10-21 09:37
Can confirm the same issue since yesterday on our system.

**Comment by dhiller** [comment] 2015-10-21 14:55
Same here, if we can help, we'd be lucky to provide you with more details.

**Comment by niick** [comment] 2015-10-22 00:42
The fix for this should be to change the Content-Type on the POST request being to "application/json" .

I can see the request is currently using 
    Content-Type:   text/html

Since Bitbucket Server 4.0, we have enabled XSRF prevention by default on all Rest resources.

More information on this can be found here: https://confluence.atlassian.com/bitbucketserver/how-to-update-your-add-on-779302412.html#Howtoupdateyouradd-on-XSRFProtectionenabledbydefault

Hopefully passing in contentType: "application/json" to the POST method in [jenkins-pr-trigger-button.js](https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook/blob/master/src/main/resources/static/jenkins-pr-triggerbutton.js#L23) should set the content-type header for that request.

**Comment by lobermann** [comment] 2015-10-29 13:34
Is there already a workaround or something to get this going again? Until the official fix is ready.

**Comment by JonMR** [comment] 2015-11-24 16:44
I opened PR #162 to fix this.  Seems to work in my local testing.

**Comment by dhiller** [comment] 2015-12-07 13:40
We tried PR #162, works for us too.

**Comment by itay** [comment] 2015-12-15 03:03
We're also stuck with this issue at the moment - it would be great to get a new release.

**Comment by marianuspotratz** [comment] 2015-12-15 16:31
I'm also affected by this and would like to add that I'm currently running a snapshot build of #162 just fine. I'd appreciate a release as well, though.

**Comment by lobermann** [comment] 2015-12-15 17:50
I would also appreciate if there would be a new release with this PR in it. To have our normal dev workflow back up and running.

**Comment by hanshuebner** [comment] 2015-12-18 13:21
Any chance to see this going into a release soon?  We have the problem as well.

**Comment by mikesir87** [comment] 2015-12-18 14:43
I'm sorry all that it's taken a while to get this resolved.  I've merged the PR, will test locally, and push a new release over the weekend.

**Comment by itay** [comment] 2016-01-05 20:03
@mikesir87 any update on pushing a release? I know people here really want us to update the plugin :)

**Comment by mikesir87** [comment] 2016-01-05 21:18
@itay Thanks for checking in and giving a smiley, although I'm sure it's been frustrating waiting for the update.  I was hoping to do it earlier, but got caught up with the holidays.

BUT... the release has just been pushed to the Marketplace, so it should be showing up for you shortly.  Thanks!

Once it's been confirmed in the deployed version of the code, I'll close this issue.

**Comment by marianuspotratz** [comment] 2016-01-07 10:45
I can confirm that it works with version 3.0.1.

**Comment by leonsim** [comment] 2016-01-07 15:19
Thanks @mikesir87 It seems the new version is on Marketplace, and it works.

**Comment by mikesir87** [comment] 2016-01-07 18:32
You're welcome all!  I'm sorry it took so long to get out there.

**Closed by mikesir87** 2016-01-07 18:32 UTC

**Comment by lobermann** [comment] 2016-01-11 14:13
I can also confirm it working. Thanks a lot @mikesir87 !
