### ISSUE TITLE
getting stack trace when trying to notify jenkins

### ISSUE THREAD

**Issue by TD-4242** [Nerdwin15/stash-jenkins-postreceive-webhook#145] opened 2015-08-06 15:55 UTC
Not sure what this means, I have keys set up and the clone link is ssh.

```
2015-08-06 15:49:30,333 ERROR [JenkinsWebhook:thread-12] @13W8V84x949x5013x0 g6xxrc 192.168.1.100 SSH - git-receive-pack '/poc/test.git' com.nerdwin15.stash.webhook.Notifier Error getting Jenkins URL
java.lang.IllegalStateException: There were no SSH clone links generated for repository POC/test
        at com.atlassian.stash.internal.ssh.service.DefaultSshCloneUrlResolver.getCloneUrl(DefaultSshCloneUrlResolver.java:37) ~[na:na]
        at com.nerdwin15.stash.webhook.Notifier$2.perform(Notifier.java:258) ~[plugin.189253547604078990.stash-webhook-jenkins-2.7.0_1438016135000.jar:na]
        at com.nerdwin15.stash.webhook.Notifier$2.perform(Notifier.java:255) ~[plugin.189253547604078990.stash-webhook-jenkins-2.7.0_1438016135000.jar:na]
        at com.atlassian.stash.internal.user.DefaultEscalatedSecurityContext.call(DefaultEscalatedSecurityContext.java:51) ~[stash-service-impl-3.11.0.jar:na]
        at com.atlassian.stash.internal.user.DefaultSecurityService.doWithPermission(DefaultSecurityService.java:77) ~[stash-service-impl-3.11.0.jar:na]
        at com.nerdwin15.stash.webhook.Notifier.getUrl(Notifier.java:255) [plugin.189253547604078990.stash-webhook-jenkins-2.7.0_1438016135000.jar:na]
        at com.nerdwin15.stash.webhook.Notifier.notify(Notifier.java:196) [plugin.189253547604078990.stash-webhook-jenkins-2.7.0_1438016135000.jar:na]
        at com.nerdwin15.stash.webhook.Notifier.notify(Notifier.java:165) [plugin.189253547604078990.stash-webhook-jenkins-2.7.0_1438016135000.jar:na]
        at com.nerdwin15.stash.webhook.Notifier$1.call(Notifier.java:144) [plugin.189253547604078990.stash-webhook-jenkins-2.7.0_1438016135000.jar:na]
        at com.nerdwin15.stash.webhook.Notifier$1.call(Notifier.java:141) [plugin.189253547604078990.stash-webhook-jenkins-2.7.0_1438016135000.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
        ... 43 frames trimmed
```

**Comment by mikesir87** [comment] 2015-08-07 03:30
Duplicate of #133 (at least the stack trace is). Will continue conversation there.

**Closed by mikesir87** 2015-08-07 03:30 UTC

**Comment by mtv-jira** [comment] 2015-10-05 17:33
Having the same problem with Stash 3.11.2, wasn't happening in 3.5.0.

Tried changing the Repo Clone URL type to Custom, with the same URL, but type reverts to SSH upon save.
